server:
  port: 8080

spring:
  datasource:
    username: loan
    password: 123456
    url: jdbc:mysql://192.168.0.189:3306/qingsongdai
    driver-class-name: com.mysql.cj.jdbc.Driver



mybatis:
  typeAliasesPackage: p2ploan.loan.entity
  mapperLocations: classpath:mapper/*.xml

